SET STEP ON
CLOSE DATABASES
USE f:\g\bible2 SHARED
replace sdperf WITH 5 FOR ALLTRIM(pattern)=='D398R'
replace soperf WITH 86 FOR ALLTRIM(pattern)=='CMA62'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='D35CA'
replace soperf WITH 36 FOR ALLTRIM(pattern)=='F351P'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='H37NA'
replace soperf WITH 36 FOR ALLTRIM(pattern)=='T183N'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='M37HB'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='H284S'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F38RF'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398K'
replace soperf WITH 52 FOR ALLTRIM(pattern)=='D349M'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398E'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398F'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398M'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398R'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398Q'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398P'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398N'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398U'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='F398V'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='M888Q'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='M888R'
replace soperf WITH 16 FOR ALLTRIM(pattern)=='D398R'
replace soperf WITH 116 FOR ALLTRIM(pattern)=='T2HY72X'
replace soperf WITH 116 FOR ALLTRIM(pattern)=='T2HY73X'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='9013X'
replace soperf WITH 4 FOR ALLTRIM(pattern)=='9014X'
CLOSE DATABASES
